name: Test Action
# Controls when the action will run.

on:
#Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    
#Allows you to run this workflow manually from the Actios tab
#Workflow
    
#A workflow contains a single job called "build" 
jobs:
  #This workflow contains a single job called "build"
  build:
    #The type of runner that the job will run on
    
    runs-on: ubuntu-latest
    
    #Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          
      - name: Check commands
        run: pwd
          
      - name: Check ls
        run: pwd
        
        #Runs a set of commands using the runners shell
      - name: Install surge
        run: npm install -g surge
      
      - name: Deploy website on surge
        run: surge ./ testsagar.surge.sh/ --token ${{secrets.TEST_SURGE_TOKEN}}
